version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - '3001:3001'  # Map port 3001 of the container to port 3001 on the host
    depends_on:
      - db

  db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGODB_URI=<your-mongodb-uri>